### ISSUE TITLE
When being logged out it says welcome strange instead of welccome strangeR

### ISSUE THREAD

**Issue by Monoverde888** [AndreMor955/dashboard#2]
tdlr: ~~welcome strange~~ welcome strange**R**

**Comment by Monoverde888** [comment]
Also the page title is Document

**Comment by AndreMor955** [comment]
Well thanks for the spell check.
And I'll be adding custom titles soon, possibly when this dashboard gets better.

**Comment by AndreMor955** [comment]
[Done.](https://github.com/AndreMor955/dashboard/commit/3aebc284a0255621c8bfb0ee6d214ad256151052)
